name: install-python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.11", "3.10", "3.9"]
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v5
      # https://github.com/marketplace/actions/setup-python
      with:
        python-version: '${{ matrix.python-version }}'

    - name: 'Just call --help with Python v${{ matrix.python-version }}'
      run: |
        python3 django_yunohost_integration/install_python/install_python.py --help

    - name: 'Call install python script with Python v${{ matrix.python-version }}'
      env:
        PYTHONUNBUFFERED: 1
        PYTHONWARNINGS: always
      run: |
        sudo python3 django_yunohost_integration/install_python/install_python.py -vv

    - name: 'Test the installed interpreter'
      run: |
        $(python3 django_yunohost_integration/install_python/install_python.py) -VV
