# https://github.com/actions/setup-python

name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    name: 'Python ${{ matrix.python-version }} Django ${{ matrix.django }}'
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.10", "3.9"]
        django: ["4.1", "4.0"]
    steps:
    - name: Checkout
      run: |
        echo $GITHUB_REF $GITHUB_SHA
        git clone --depth 1 https://github.com/$GITHUB_REPOSITORY.git .
        git fetch origin $GITHUB_SHA:temporary-ci-branch
        git checkout $GITHUB_SHA || (git fetch && git checkout $GITHUB_SHA)

    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v4
      # https://github.com/marketplace/actions/setup-python
      with:
        python-version: '${{ matrix.python-version }}'
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: '**/poetry.lock'

    - name: 'Bootstrap'
      run: |
        python3 devshell.py quit

    - name: 'List installed packages'
      run: |
        python3 devshell.py list_venv_packages

    - name: 'Run tests with Python ${{ matrix.python-version }} Django ${{ matrix.django }}'
      run: python3 devshell.py tox -e python-django${{ matrix.django }}

    - name: 'Run safety check with Python v${{ matrix.python-version }}'
      run: |
        python3 devshell.py safety
